#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

start_service() {
	local enabled

	config_load 'cake-adapt'
	config_get_bool enabled 'main' 'enabled' 0
	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance
	procd_set_param command /usr/sbin/cake-adapt
	procd_set_param respawn
	procd_set_param term_timeout 5
	procd_set_param file /etc/config/cake-adapt
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger 'cake-adapt'
}

reload_service() {
	stop
	start
}
