#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

start_service() {
	local enabled

	if ! config_load 'cake-adapt'; then
		logger -t cake-adapt -p daemon.err \
			"configuration /etc/config/cake-adapt could not be loaded; not starting"
		return 1
	fi
	config_get_bool enabled 'main' 'enabled' 0
	if [ "$enabled" -ne 1 ]; then
		logger -t cake-adapt -p daemon.notice \
			"disabled by configuration; not starting"
		return 0
	fi

	procd_open_instance
	procd_set_param command /usr/sbin/cake-adapt
	procd_set_param respawn
	procd_set_param term_timeout 5
	procd_set_param file /etc/config/cake-adapt
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger 'cake-adapt'
}

reload_service() {
	stop
	start
}
