#ifndef DEFAULTS_H_INCLUDED
#define DEFAULTS_H_INCLUDED

#include "constants.h"

struct config;

#define DEFAULT_SECTION "main"
#define DEFAULT_CONFIG_PATH "/etc/config/" UCI_PACKAGE
#define DEFAULT_LOG_DIRECTORY "/var/log"
#define DEFAULT_LOG_FILE_BASE PROGRAM_NAME
#define DEFAULT_FPING_TIMEOUT_MILLISECONDS "10000"

/* Fixed operational defaults, separate from configurable UCI values. */
#define CHILD_STOP_ATTEMPTS 50U
#define CHILD_STOP_INTERVAL_NANOSECONDS \
    (10L * (long)NANOSECONDS_PER_MILLISECOND)
#define INITIAL_ONE_WAY_BASELINE_MICROSECONDS \
    (100U * MILLISECOND)
#define NETLINK_RESPONSE_TIMEOUT_MILLISECONDS \
    ((int)MILLISECONDS_PER_SECOND)
#define SATURATION_ENTER_PERCENT 90U
#define SATURATION_EXIT_PERCENT 80U
#define SATURATION_CONFIRMATION_SAMPLES 3U
#define RECOVERY_CONFIRMATION_SAMPLES 3U

void defaults_apply(struct config *config);

#endif
